module.exports = Object.freeze({
  CLASS_IN_DAY: [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "A",
    "B",
    "C",
    "D",
  ],
  DAY_IN_WEEK: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  RULES: ["priority", "people", "time"],
  PRIORITY: { 本系優先: 0, 高年級優先: 0, 抽籤: 0 },
  PEOPLE: { "1~10": 0, "11~20": 0, "21~30": 0, "31~40": 0, "40~": 0 },
});
